config/routes.rb
Simplekanban::Application.routes.draw do
  resources :stories

  resources :statuses
  
  resources :projects, :only => [:show], :requirement => {:id => 'default'}
  
  root :to => 'projects#show', :id => 'default'

end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects/default
  def show
    redirect_to project_url('default') and return unless params[:id] == 'default'

    @project = "Default"

    respond_to do |format|
      format.html # show.html.erb
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @statuses }
    end
  end

  # GET /statuses/1
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /statuses/new
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to(@status, :notice => 'Status was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /statuses/1
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to(@status, :notice => 'Status was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /statuses/1
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to(statuses_url) }
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @stories }
    end
  end

  # GET /stories/1
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /stories/new
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to(@story, :notice => 'Story was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /stories/1
  def update
    @story = Story.find(params[:id])
    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to(@story, :notice => 'Story was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to(stories_url) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
Written by Stephan Schmidt, who can be found on Twitter <a href="http://twitter.com/codemonkeyism">http://twitter.com/codemonkeyism</a>,
Blog at <a href="http://www.codemonkeyism.com/">http://www.codemonkeyism.com</a>,  using
JQuery with the DragSort plugin<br>
This software application is Twitter-Ware. If you like it, use it, or have something to say, <b>follow me</b> and
tell me on Twitter at @codemonkeyism<br>
    The newest version can be found on <a href="http://www.simple-kanban.com/">www.simple-kanban.com</a>

<p>Extended to use Rails 3 and SQLite for saving Story card and Status by <a href="http://www.twitter.com/sathish316">@sathish316</a><br>
Code available at <a href="https://github.com/0s30s1s/simplekanban">Github</a>.
Demo app deployed in <a href="http://simplekanbanwall.heroku.com">Heroku</a>
</p>

</div>
<!--
	 Copyright (c) 2009 Stephan Schmidt

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE
-->

app/views/layouts/_header.html.erb
<header>
	<h1>Kanban Board</h1>
	<nav>
		<%= link_to 'Wall', root_path %> | 
		<%= link_to 'Stories', stories_path %> |
		<%= link_to 'Status', statuses_path %>
	</nat>
	<p></p>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Kanban</title>
</head>
<body>
	<div class='container'>
		<%= render 'layouts/header' %>
		<section>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.code %></td>
    <td><%= status.name %></td>
    <td><%= status.color %></td>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @status.code %>
</p>

<p>
  <b>Name:</b>
  <%= @status.name %>
</p>

<p>
  <b>Color:</b>
  <%= @status.color %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status_code %><br />
    <%= f.text_field :status_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Name</th>
    <th>Status code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= story.number %></td>
    <td><%= story.name %></td>
    <td><%= story.status_code %></td>
    <td><%= link_to 'Show', story %></td>
    <td><%= link_to 'Edit', edit_story_path(story) %></td>
    <td><%= link_to 'Destroy', story, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @story.number %>
</p>

<p>
  <b>Name:</b>
  <%= @story.name %>
</p>

<p>
  <b>Status code:</b>
  <%= @story.status_code %>
</p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>